# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
magick = "1.6.0"

[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
  "rust",
  "python",
  "lua",
  "c",
  "cpp",
  "d",
  "toml",
  "markdown"
]
auto_install = true

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.19.1"
"rocks-git.nvim" = "1.3.1"
"rocks-config.nvim" = "1.2.3"
"onedarkpro.nvim" = "0.8.0"
"telescope.nvim" = "scm"
"lualine.nvim" = "scm"
"neoscroll.nvim" = "scm"
"trouble.nvim" = "2.10.0"
"bufferline.nvim" = "4.5.2"
vimpeccable = "scm"
nvim-autopairs = "scm"
"none-ls.nvim" = "scm"
nvim-lspconfig = "0.1.7"
"indent-blankline.nvim" = "3.5.4"
"project.nvim" = "scm"
"marks.nvim" = "scm"
"lspkind.nvim" = "scm"
"image.nvim" = "1.2.0"
tree-sitter-toml = "scm"
cmp-path = "scm"
tree-sitter-java = "scm"
neorg = "8.4.0"
"dressing.nvim" = "2.2.0"
"otter.nvim" = "1.12.1"
"rainbow-delimiters.nvim" = "0.3.0"

[plugins.nvim-cmp ]
git = "hrsh7th/nvim-cmp"
rev = "v0.0.1"

[plugins."symbols-outline.nvim"]
git = "simrat39/symbols-outline.nvim"

[plugins.vim-tmux-navigator]
git = "christoomey/vim-tmux-navigator"
rev = "v1.0^{}"

[plugins.skim]
git = "lotabout/skim"
rev = "v0.9.4"

[plugins."skim.vim"]
git = "lotabout/skim.vim"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.3^{}"

[plugins."indentpython.vim"]
git = "vim-scripts/indentpython.vim"
rev = "0.3^{}"

[plugins.emmet-vim]
git = "mattn/emmet-vim"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.9"

[plugins."cheatsheet.nvim"]
git = "sudormrfbin/cheatsheet.nvim"

[plugins.vim-snippets]
git = "honza/vim-snippets"
rev = "1.0.0"

[plugins.nvim-lsp-file-operations]
git = "antosha417/nvim-lsp-file-operations"

[plugins."onedark.nvim"]
git = "navarasu/onedark.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.7"

[plugins.nerdcommenter]
git = "preservim/nerdcommenter"
rev = "2.7.0^{}"

[plugins."editorconfig.nvim"]
git = "gpanders/editorconfig.nvim"
rev = "v1.4.0^{}"

[plugins.tree-sitter-norg]
git = "nvim-neorg/tree-sitter-norg"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.sniprun]
git = "michaelb/sniprun"
rev = "v1.3.9^{}"

[plugins.LuaSnip]
git = "L3MON4D3/LuaSnip"
rev = "v2.2.0"

[plugins.quarto-nvim]
git = "quarto-dev/quarto-nvim"
rev = "v0.18.2"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.8.1"

