# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
magick = "1.6.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
"rocks-git.nvim" = "2.3.1"
"rocks-config.nvim" = "3.0.0"
"onedarkpro.nvim" = "1.0.0"
"telescope.nvim" = "scm"
"lualine.nvim" = "scm"
"neoscroll.nvim" = "scm"
"trouble.nvim" = { version = "3.6.0" }
"bufferline.nvim" = { version = "4.7.0", pin = true }
"vimpeccable" = "scm"
"nvim-autopairs" = "scm"
"conform.nvim" = { version = "8.1.0", pin = true }
"none-ls.nvim" = "scm"
"none-ls-extras.nvim" = "scm"
"nvim-lspconfig" = "1.0.0"
"indent-blankline.nvim" = "3.7.2"
"project.nvim" = "scm"
"marks.nvim" = "scm"
"lspkind.nvim" = "scm"
"image.nvim" = "1.3.0"
"cmp-path" = "scm"
#"neorg" = { version = "8.4.0", opt = true, pin = true }
"dressing.nvim" = "3.0.0"
"otter.nvim" = { version = "1.12.1", opt = true, pin = true }
"rainbow-delimiters.nvim" = "0.6.2"
"tree-sitter-toml" = { version = "scm", opt = true }
nvim-lint = "scm"

[plugins.vim-arduino]
git = "stevearc/vim-arduino"
rev = "master"


[plugins.nvim-drawer]
git = "mikew/nvim-drawer"
rev = "2b1db633d9eca134502e1753e5a38974ba309fe1"

[plugins.nvim-highllight-colors]
git = "brenoprata10/nvim-highlight-colors"
rev = "a411550ef85cae467b889ba7d1a96bd78332d90e"

[plugins."webtool.nvim"]
git = "ray-x/web-tools.nvim"
rev = "eb0ac27bd3eb0beb06b7190a11e2e043049a4ccc"

[plugins."symbols-outline.nvim"]
git = "simrat39/symbols-outline.nvim"
rev = "564ee65dfc9024bdde73a6621820866987cbb256"

[plugins.vim-tmux-navigator]
git = "christoomey/vim-tmux-navigator"
rev = "v1.0^{}"

[plugins.skim]
git = "lotabout/skim"
rev = "v0.9.4"

[plugins."skim.vim"]
git = "lotabout/skim.vim"
rev = "aa2a5c44a6640843868cc5c1444abc0093e90e5a"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.7.1^{}"

[plugins."indentpython.vim"]
git = "vim-scripts/indentpython.vim"
rev = "0.3"
opt = true

[plugins.emmet-vim]
git = "mattn/emmet-vim"
rev = "6c511a8d7d2863066f32e25543e2bb99d505172c"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.15"

[plugins."cheatsheet.nvim"]
git = "sudormrfbin/cheatsheet.nvim"
rev = "9716f9aaa94dd1fd6ce59b5aae0e5f25e2a463ef"

[plugins.vim-snippets]
git = "honza/vim-snippets"
rev = "1.0.0"

[plugins.nvim-lsp-file-operations]
git = "antosha417/nvim-lsp-file-operations"
rev = "92a673de7ecaa157dd230d0128def10beb56d103"

[plugins."onedark.nvim"]
git = "navarasu/onedark.nvim"
rev = "fae34f7c635797f4bf62fb00e7d0516efa8abe37"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0^{}"

[plugins.nerdcommenter]
git = "preservim/nerdcommenter"
rev = "2.7.0^{}"

[plugins.tree-sitter-norg]
git = "nvim-neorg/tree-sitter-norg"
rev = "v0.2.6"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "master"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "00ba9dd3df89509f95437b8d595553707c46d5ea"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"
rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843"

[plugins.sniprun]
git = "michaelb/sniprun"
rev = "v1.3.9^{}"

[plugins.LuaSnip]
git = "L3MON4D3/LuaSnip"
rev = "v2.3.0^{}"

[plugins.quarto-nvim]
git = "quarto-dev/quarto-nvim"
rev = "v1.0.2"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"
rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"
rev = "c8baf3ad344c59b3abd461ecc17fc16ec44d0f7b"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.9.0"
